FROM balenalib/raspberry-pi-openjdk:8-stretch

ENV EXTRACTOR_VERSION 1.0.8
ENV KTOR_USER ktor
ENV HOME /home/$KTOR_USER
RUN useradd --create-home $KTOR_USER && \
    mkdir $HOME/app && \
    chown -R $KTOR_USER $HOME/app

WORKDIR $HOME/app
USER $KTOR_USER

COPY ./build/lib/*.jar ./
EXPOSE 8080
EXPOSE 9090

COPY ./scripts/entrypoint.sh $HOME/
ENTRYPOINT [ "/home/ktor/entrypoint.sh" ]