FROM balenalib/raspberry-pi-openjdk:8-stretch

ENV EXTRACTOR_VERSION 1.0.20
ENV KTOR_USER ktor
ENV HOME /home/$KTOR_USER
RUN useradd --create-home $KTOR_USER && \
    mkdir $HOME/app && \
    chown -R $KTOR_USER $HOME/app

USER $KTOR_USER

COPY ./build/install/StagyBeeExtractor/ $HOME/app/
EXPOSE 8443

WORKDIR $HOME/app/bin

ENTRYPOINT [ "./StagyBeeExtractor" ]